### ISSUE TITLE
Auswahl von Hochschulen

### ISSUE THREAD

**Issue by StevKanne** [thorstenwitt/mensaApp#54]

**Comment by robbirob** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.thorstenwitt.mensaapp/de.thorstenwitt.mensaapp.activity.MenuActivity}: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at de.thorstenwitt.mensaapp.activity.MenuActivity.sendMensaDataToWatch(MenuActivity.java:120)
	at de.thorstenwitt.mensaapp.activity.MenuActivity.onCreate(MenuActivity.java:116)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
	... 9 more

**Comment by thorstenwitt** [comment]
Fehler trat auf, wenn die Liste der Mensen noch nicht aufgebaut wurde (ArraySize=0) und versucht wurde die Speisekarten-Daten der Mensa-Stralsund (Index 2) zu holen.
